pool: 
  vmImage: ubuntu-24.04
trigger: 
  - main
stages: 
- stage: buildstage
  jobs:
    - job: buildjob
      steps:
      - task: Maven@4
        inputs:
         mavenPOMFile: pom.xml
         goals: validate
         jdkVersionOption: '1.17'
